apiVersion: apps/v1
kind: Deployment
metadata:
  name: shandeep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shandeep
  template:
    metadata:
      labels:
        app: shandeep
    spec:
      containers:
        - name: nginx-container
          image: shandeep04/docker_jenkins_task2:latest  # Replace with your actual Docker image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shandeep
spec:
  selector:
    app: shandeep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change to LoadBalancer if using cloud Kubernetes
